"""Application-level WebMCP support for the Waggle Workspace."""

from .demo import (
    DEMO_COOKIE_MAX_AGE,
    DEMO_COOKIE_NAME,
    DEMO_PUBLIC_PROJECT_ID,
    DemoScope,
    ensure_demo_seed,
    publicize_demo_payload,
    reset_demo,
    resolve_demo_scope,
    resolve_public_project,
    valid_demo_session_id,
)
from .projects import (
    ProjectIdentity,
    get_registered_project,
    list_registered_projects,
    normalize_git_remote,
    refresh_project_context,
    register_project,
    repository_context_for_project,
    resolve_active_project,
    resolve_project_identity,
)
from .proposals import ProposalRepository
from .workspace import (
    apply_approved_memory_change,
    authority_status,
    compile_project_brief,
    project_authority_snapshot,
    propose_memory_change,
    recall_authoritative_memory,
    review_memory_change,
)

__all__ = [
    "DEMO_COOKIE_MAX_AGE",
    "DEMO_COOKIE_NAME",
    "DEMO_PUBLIC_PROJECT_ID",
    "DemoScope",
    "ProjectIdentity",
    "ProposalRepository",
    "apply_approved_memory_change",
    "authority_status",
    "compile_project_brief",
    "ensure_demo_seed",
    "get_registered_project",
    "list_registered_projects",
    "normalize_git_remote",
    "project_authority_snapshot",
    "propose_memory_change",
    "publicize_demo_payload",
    "recall_authoritative_memory",
    "refresh_project_context",
    "register_project",
    "repository_context_for_project",
    "reset_demo",
    "resolve_active_project",
    "resolve_demo_scope",
    "resolve_project_identity",
    "resolve_public_project",
    "review_memory_change",
    "valid_demo_session_id",
]
